 

Pipeline:
  name: "My Project"
  stages:
    - stageType: "Clone"
      script: "git clone https://example.com"
      order: 0
      artifacts:
    - stageType: "Build"
      script: "build command for My Project"
      order: 1
      artifacts:
    - stageType: "Test"
      script: "test command for My Project"
      order: 2
      artifacts:
    - stageType: "Deploy"
      script: "deploy command for My Project"
      order: 3
      artifacts:
  triggers:
    - name: "Push Trigger"
      condition: "push"
