stages:
- clone
- build
- test
- test
- deploy
clone:
  stage: clone
  variables:
    GIT_URL: https://example.com
    CREDENTIAL_ID: null
  script:
  - git clone https://example.com
  - git checkout main
build:
  stage: build
  script:
  - mvn clean install
test:
  stage: test
  variables:
    TEST_CLASSES: null
  script:
  - mvn verify
deploy:
  stage: deploy
  only:
  - push
  script:
  - docker-compose up
