 

stages:
  - Clone
  - Build
  - Test
  - Deploy
 

  clone:
  stage: clone
  script:
    - git clone https://example.com
  build:
  stage: build
  script:
    - build command for My Project
  test:
  stage: test
  script:
    - test command for My Project
  deploy:
  stage: deploy
  script:
    - deploy command for My Project

triggers:
    - name: "Push Trigger"
      condition: "push"

