 
stages:
  - Clone
  - Build
  - Test
  - Test
  - Deploy

clone:
  stage: clone
  script:
    - git clone https://example.com
build:
  stage: build
  script:
    - mvn clean install
test:
  stage: test
  script:
    - mvn test
test:
  stage: test
  script:
    - mvn verify
deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - "push"

